### ISSUE TITLE
Pulled latest but none of the assets load?

### ISSUE THREAD

**Issue by RobertMassart** [GlassBeaver/CoverSystem#2]
Failed to load map!
../../../../../../RM/UE422/CoverSystemTest/Content/MainMap.umap appears to be an asset file.

Do you know of to fix this?

**Comment by GlassBeaver** [comment]
Did you clone the repo locally or downloaded a zip? Try cloning it, I the same issue IIRC that was resolved by cloning.

**Comment by RobertMassart** [comment]
Yes, I just did a clone and it works.  Really strange all assets are small number of bytes in the zip file which gave me hint to clone it.

**Comment by GlassBeaver** [comment]
Assets being only a few bytes is probably because I'm using git-lfs for storing binary files - a zip download likely excludes them.
